/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWorkflowIdRouteImport } from './routes/w.$workflowId'
import { Route as ApiPublicWorkerCompleteRouteImport } from './routes/api/public/worker/complete'
import { Route as ApiPublicWorkerClaimRouteImport } from './routes/api/public/worker/claim'
import { Route as ApiPublicCronEnqueueMonitorsRouteImport } from './routes/api/public/cron/enqueue-monitors'
import { Route as ApiPublicCrossKitTaskRouteImport } from './routes/api/public/cross/kit/task'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkflowIdRoute = WWorkflowIdRouteImport.update({
  id: '/w/$workflowId',
  path: '/w/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerCompleteRoute = ApiPublicWorkerCompleteRouteImport.update({
  id: '/api/public/worker/complete',
  path: '/api/public/worker/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerClaimRoute = ApiPublicWorkerClaimRouteImport.update({
  id: '/api/public/worker/claim',
  path: '/api/public/worker/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronEnqueueMonitorsRoute =
  ApiPublicCronEnqueueMonitorsRouteImport.update({
    id: '/api/public/cron/enqueue-monitors',
    path: '/api/public/cron/enqueue-monitors',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCrossKitTaskRoute = ApiPublicCrossKitTaskRouteImport.update({
  id: '/api/public/cross/kit/task',
  path: '/api/public/cross/kit/task',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/w/$workflowId': typeof WWorkflowIdRoute
  '/api/public/cron/enqueue-monitors': typeof ApiPublicCronEnqueueMonitorsRoute
  '/api/public/worker/claim': typeof ApiPublicWorkerClaimRoute
  '/api/public/worker/complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/cross/kit/task': typeof ApiPublicCrossKitTaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/w/$workflowId': typeof WWorkflowIdRoute
  '/api/public/cron/enqueue-monitors': typeof ApiPublicCronEnqueueMonitorsRoute
  '/api/public/worker/claim': typeof ApiPublicWorkerClaimRoute
  '/api/public/worker/complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/cross/kit/task': typeof ApiPublicCrossKitTaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/w/$workflowId': typeof WWorkflowIdRoute
  '/api/public/cron/enqueue-monitors': typeof ApiPublicCronEnqueueMonitorsRoute
  '/api/public/worker/claim': typeof ApiPublicWorkerClaimRoute
  '/api/public/worker/complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/cross/kit/task': typeof ApiPublicCrossKitTaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/w/$workflowId'
    | '/api/public/cron/enqueue-monitors'
    | '/api/public/worker/claim'
    | '/api/public/worker/complete'
    | '/api/public/cross/kit/task'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/w/$workflowId'
    | '/api/public/cron/enqueue-monitors'
    | '/api/public/worker/claim'
    | '/api/public/worker/complete'
    | '/api/public/cross/kit/task'
  id:
    | '__root__'
    | '/'
    | '/w/$workflowId'
    | '/api/public/cron/enqueue-monitors'
    | '/api/public/worker/claim'
    | '/api/public/worker/complete'
    | '/api/public/cross/kit/task'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WWorkflowIdRoute: typeof WWorkflowIdRoute
  ApiPublicCronEnqueueMonitorsRoute: typeof ApiPublicCronEnqueueMonitorsRoute
  ApiPublicWorkerClaimRoute: typeof ApiPublicWorkerClaimRoute
  ApiPublicWorkerCompleteRoute: typeof ApiPublicWorkerCompleteRoute
  ApiPublicCrossKitTaskRoute: typeof ApiPublicCrossKitTaskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workflowId': {
      id: '/w/$workflowId'
      path: '/w/$workflowId'
      fullPath: '/w/$workflowId'
      preLoaderRoute: typeof WWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/complete': {
      id: '/api/public/worker/complete'
      path: '/api/public/worker/complete'
      fullPath: '/api/public/worker/complete'
      preLoaderRoute: typeof ApiPublicWorkerCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/claim': {
      id: '/api/public/worker/claim'
      path: '/api/public/worker/claim'
      fullPath: '/api/public/worker/claim'
      preLoaderRoute: typeof ApiPublicWorkerClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/enqueue-monitors': {
      id: '/api/public/cron/enqueue-monitors'
      path: '/api/public/cron/enqueue-monitors'
      fullPath: '/api/public/cron/enqueue-monitors'
      preLoaderRoute: typeof ApiPublicCronEnqueueMonitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cross/kit/task': {
      id: '/api/public/cross/kit/task'
      path: '/api/public/cross/kit/task'
      fullPath: '/api/public/cross/kit/task'
      preLoaderRoute: typeof ApiPublicCrossKitTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WWorkflowIdRoute: WWorkflowIdRoute,
  ApiPublicCronEnqueueMonitorsRoute: ApiPublicCronEnqueueMonitorsRoute,
  ApiPublicWorkerClaimRoute: ApiPublicWorkerClaimRoute,
  ApiPublicWorkerCompleteRoute: ApiPublicWorkerCompleteRoute,
  ApiPublicCrossKitTaskRoute: ApiPublicCrossKitTaskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
