/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedWWorkflowIdRouteImport } from './routes/_authenticated.w.$workflowId'
import { Route as ApiPublicWorkerRecordStatusRouteImport } from './routes/api/public/worker/record-status'
import { Route as ApiPublicWorkerRecordClaimRouteImport } from './routes/api/public/worker/record-claim'
import { Route as ApiPublicWorkerCompleteRouteImport } from './routes/api/public/worker/complete'
import { Route as ApiPublicWorkerClaimRouteImport } from './routes/api/public/worker/claim'
import { Route as ApiPublicCronEnqueueMonitorsRouteImport } from './routes/api/public/cron/enqueue-monitors'
import { Route as ApiPublicCrossKitTaskRouteImport } from './routes/api/public/cross/kit/task'
import { Route as ApiPublicCrossKitTaskTask_idLogRouteImport } from './routes/api/public/cross/kit/task/$task_id/log'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWWorkflowIdRoute =
  AuthenticatedWWorkflowIdRouteImport.update({
    id: '/w/$workflowId',
    path: '/w/$workflowId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWorkerRecordStatusRoute =
  ApiPublicWorkerRecordStatusRouteImport.update({
    id: '/api/public/worker/record-status',
    path: '/api/public/worker/record-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerRecordClaimRoute =
  ApiPublicWorkerRecordClaimRouteImport.update({
    id: '/api/public/worker/record-claim',
    path: '/api/public/worker/record-claim',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerCompleteRoute = ApiPublicWorkerCompleteRouteImport.update({
  id: '/api/public/worker/complete',
  path: '/api/public/worker/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerClaimRoute = ApiPublicWorkerClaimRouteImport.update({
  id: '/api/public/worker/claim',
  path: '/api/public/worker/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronEnqueueMonitorsRoute =
  ApiPublicCronEnqueueMonitorsRouteImport.update({
    id: '/api/public/cron/enqueue-monitors',
    path: '/api/public/cron/enqueue-monitors',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCrossKitTaskRoute = ApiPublicCrossKitTaskRouteImport.update({
  id: '/api/public/cross/kit/task',
  path: '/api/public/cross/kit/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrossKitTaskTask_idLogRoute =
  ApiPublicCrossKitTaskTask_idLogRouteImport.update({
    id: '/$task_id/log',
    path: '/$task_id/log',
    getParentRoute: () => ApiPublicCrossKitTaskRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/w/$workflowId': typeof AuthenticatedWWorkflowIdRoute
  '/api/public/cron/enqueue-monitors': typeof ApiPublicCronEnqueueMonitorsRoute
  '/api/public/worker/claim': typeof ApiPublicWorkerClaimRoute
  '/api/public/worker/complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/worker/record-claim': typeof ApiPublicWorkerRecordClaimRoute
  '/api/public/worker/record-status': typeof ApiPublicWorkerRecordStatusRoute
  '/api/public/cross/kit/task': typeof ApiPublicCrossKitTaskRouteWithChildren
  '/api/public/cross/kit/task/$task_id/log': typeof ApiPublicCrossKitTaskTask_idLogRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/': typeof AuthenticatedIndexRoute
  '/w/$workflowId': typeof AuthenticatedWWorkflowIdRoute
  '/api/public/cron/enqueue-monitors': typeof ApiPublicCronEnqueueMonitorsRoute
  '/api/public/worker/claim': typeof ApiPublicWorkerClaimRoute
  '/api/public/worker/complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/worker/record-claim': typeof ApiPublicWorkerRecordClaimRoute
  '/api/public/worker/record-status': typeof ApiPublicWorkerRecordStatusRoute
  '/api/public/cross/kit/task': typeof ApiPublicCrossKitTaskRouteWithChildren
  '/api/public/cross/kit/task/$task_id/log': typeof ApiPublicCrossKitTaskTask_idLogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/w/$workflowId': typeof AuthenticatedWWorkflowIdRoute
  '/api/public/cron/enqueue-monitors': typeof ApiPublicCronEnqueueMonitorsRoute
  '/api/public/worker/claim': typeof ApiPublicWorkerClaimRoute
  '/api/public/worker/complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/worker/record-claim': typeof ApiPublicWorkerRecordClaimRoute
  '/api/public/worker/record-status': typeof ApiPublicWorkerRecordStatusRoute
  '/api/public/cross/kit/task': typeof ApiPublicCrossKitTaskRouteWithChildren
  '/api/public/cross/kit/task/$task_id/log': typeof ApiPublicCrossKitTaskTask_idLogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/transcribe'
    | '/w/$workflowId'
    | '/api/public/cron/enqueue-monitors'
    | '/api/public/worker/claim'
    | '/api/public/worker/complete'
    | '/api/public/worker/record-claim'
    | '/api/public/worker/record-status'
    | '/api/public/cross/kit/task'
    | '/api/public/cross/kit/task/$task_id/log'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/api/transcribe'
    | '/'
    | '/w/$workflowId'
    | '/api/public/cron/enqueue-monitors'
    | '/api/public/worker/claim'
    | '/api/public/worker/complete'
    | '/api/public/worker/record-claim'
    | '/api/public/worker/record-status'
    | '/api/public/cross/kit/task'
    | '/api/public/cross/kit/task/$task_id/log'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/api/transcribe'
    | '/_authenticated/'
    | '/_authenticated/w/$workflowId'
    | '/api/public/cron/enqueue-monitors'
    | '/api/public/worker/claim'
    | '/api/public/worker/complete'
    | '/api/public/worker/record-claim'
    | '/api/public/worker/record-status'
    | '/api/public/cross/kit/task'
    | '/api/public/cross/kit/task/$task_id/log'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiPublicCronEnqueueMonitorsRoute: typeof ApiPublicCronEnqueueMonitorsRoute
  ApiPublicWorkerClaimRoute: typeof ApiPublicWorkerClaimRoute
  ApiPublicWorkerCompleteRoute: typeof ApiPublicWorkerCompleteRoute
  ApiPublicWorkerRecordClaimRoute: typeof ApiPublicWorkerRecordClaimRoute
  ApiPublicWorkerRecordStatusRoute: typeof ApiPublicWorkerRecordStatusRoute
  ApiPublicCrossKitTaskRoute: typeof ApiPublicCrossKitTaskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/w/$workflowId': {
      id: '/_authenticated/w/$workflowId'
      path: '/w/$workflowId'
      fullPath: '/w/$workflowId'
      preLoaderRoute: typeof AuthenticatedWWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/worker/record-status': {
      id: '/api/public/worker/record-status'
      path: '/api/public/worker/record-status'
      fullPath: '/api/public/worker/record-status'
      preLoaderRoute: typeof ApiPublicWorkerRecordStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/record-claim': {
      id: '/api/public/worker/record-claim'
      path: '/api/public/worker/record-claim'
      fullPath: '/api/public/worker/record-claim'
      preLoaderRoute: typeof ApiPublicWorkerRecordClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/complete': {
      id: '/api/public/worker/complete'
      path: '/api/public/worker/complete'
      fullPath: '/api/public/worker/complete'
      preLoaderRoute: typeof ApiPublicWorkerCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/claim': {
      id: '/api/public/worker/claim'
      path: '/api/public/worker/claim'
      fullPath: '/api/public/worker/claim'
      preLoaderRoute: typeof ApiPublicWorkerClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/enqueue-monitors': {
      id: '/api/public/cron/enqueue-monitors'
      path: '/api/public/cron/enqueue-monitors'
      fullPath: '/api/public/cron/enqueue-monitors'
      preLoaderRoute: typeof ApiPublicCronEnqueueMonitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cross/kit/task': {
      id: '/api/public/cross/kit/task'
      path: '/api/public/cross/kit/task'
      fullPath: '/api/public/cross/kit/task'
      preLoaderRoute: typeof ApiPublicCrossKitTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cross/kit/task/$task_id/log': {
      id: '/api/public/cross/kit/task/$task_id/log'
      path: '/$task_id/log'
      fullPath: '/api/public/cross/kit/task/$task_id/log'
      preLoaderRoute: typeof ApiPublicCrossKitTaskTask_idLogRouteImport
      parentRoute: typeof ApiPublicCrossKitTaskRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWWorkflowIdRoute: typeof AuthenticatedWWorkflowIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWWorkflowIdRoute: AuthenticatedWWorkflowIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicCrossKitTaskRouteChildren {
  ApiPublicCrossKitTaskTask_idLogRoute: typeof ApiPublicCrossKitTaskTask_idLogRoute
}

const ApiPublicCrossKitTaskRouteChildren: ApiPublicCrossKitTaskRouteChildren = {
  ApiPublicCrossKitTaskTask_idLogRoute: ApiPublicCrossKitTaskTask_idLogRoute,
}

const ApiPublicCrossKitTaskRouteWithChildren =
  ApiPublicCrossKitTaskRoute._addFileChildren(
    ApiPublicCrossKitTaskRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiPublicCronEnqueueMonitorsRoute: ApiPublicCronEnqueueMonitorsRoute,
  ApiPublicWorkerClaimRoute: ApiPublicWorkerClaimRoute,
  ApiPublicWorkerCompleteRoute: ApiPublicWorkerCompleteRoute,
  ApiPublicWorkerRecordClaimRoute: ApiPublicWorkerRecordClaimRoute,
  ApiPublicWorkerRecordStatusRoute: ApiPublicWorkerRecordStatusRoute,
  ApiPublicCrossKitTaskRoute: ApiPublicCrossKitTaskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
